# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AC-iOS-Final' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'SnapKit'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'Kingfisher'
pod 'Toucan'
pod 'IQKeyboardManagerSwift'
pod 'SVProgressHUD'

  # Pods for AC-iOS-Final

end
